### ISSUE TITLE
migrate CI to github actions

### ISSUE THREAD

**Issue by pkienzle** [reflectometry/refl1d#99]

**Comment by andyfaff** [comment]
If you want to make Linux wheels that are usable on pypi you can use the quay `manylinux2010_x86_64` and 2014 docker images.

**Comment by pkienzle** [comment]
I generally haven't worried about linux wheels since the build is straightforward. I'm not sure if linux wheels will add more problems than they solve.

Do you have examples of how to set them up?

Also, I was reading yesterday that the numpy bindings used in one of the extensions might be numpy version dependent, and therefore it is better to build for the platform (though that begs the question of what happens with the windows and mac wheels, so the answer there is that we shouldn't be using the numpy C api).

**Comment by andyfaff** [comment]
Code I use in the github actions script:
```
  linux_wheels:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 2
      matrix:
        PLAT: ["manylinux2010_x86_64", "manylinux2014_x86_64"]

    steps:
    - uses: actions/checkout@v2
    - name: Make Linux Wheel
      run: |
        docker run --rm -e="PLAT=${{ matrix.PLAT }}" -v $(pwd):/io quay.io/pypa/${{ matrix.PLAT }} /bin/bash /io/tools/build_manylinux_wheels.sh
    - uses: actions/upload-artifact@v1
      with:
        name: refnx-wheel
        path: dist/
```
